# Ejercicios Modulo 5. Librerías especializadas en datos (Soluciones)

Consideraciones a tener en cuenta: 

* Guardar este documento con el siguiente formato para su entrega: __M5_05_nombre_apellido1_apellido2__
* Realizar los ejercicios con las herramientas vistas en las sesiones. 
* Comentar el código
* Utilizar nombres de variables apropiados, si vais a guardar una nota, llamar a esa variable nota, no n o x

**1) Trabajemos con NumPy**

* Importa numpy y usa un alias para poder utilizar sus recursos
* Crea un array de elementos (del 10 al 100)
* Invertir el array
* Crear un array 3x3 con valores de 0 a 8
* Crear un array identidad de 6x6
* Crear un array con valores al azar con forma 3x3x3
* Crear dos arrays con valores al azar A y B, verificar si son iguales (hay varias opciones, investigar)

In [40]:
# Completa el ejercicio aquí
import numpy as np
matriz1 = np.arange(10,101)
print(matriz1)
matriz2 = np.flip(matriz1, 0)
print(matriz2)
matriz3 = np.arange(0,9).reshape(3,3)
print(matriz3)
identidad6x6 = np.identity(6)
print(identidad6x6)
aleatoria3x3x3 = np.random.randint(1, 1000, size = [3,3,3])
print(aleatoria3x3x3)
A = np.random.randint(0, 1000, size = (10,10))
B = np.random.randint(0, 1000, size = (10,10))
#Opcion de comparación 1 - Función integrada en numpy
print(f"Las matrices A y B {"" if np.array_equal(A, B) == True else "no"} son iguales")
#Opción de comparación 2: utilizando comparación elemento a elemento.
print(np.all(A == B, where = True))

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[[569 380 170]
  [641 602 239]
  [834 252 529]]

 [[874 514  56]
  [949 604 627]
  [586 582 869]]

 [[

**2) Sigamos con NumPy**

* Crear un array de 100 elementos aleatorios comprendidos entre 1 y 1000 (pueden ser números enteros).
* Este array se llamara dólares
* Crear otro array llamado euros
* Realizar la conversión de los precios en dólares del primer array al segundo array en euros. Se puede serguir la siguiente conversión:
    - 1 EUR = 1,14362 USD
    - 1 USD = 0,874413 EUR
* Mostrar el resultado del array de euros pero redondeado a 2 decimales

In [51]:
# Completa el ejercicio aquí
dolares = np.random.randint(1, 1000, 100)
print(dolares)
euros = dolares * 0.874413
print(np.round(euros, 2))


[793 762 214 430 567 763 464 807 513 885 809  56 163 689 251 815 131 574
 489 669 520 382 357  99 776 457 918 957 699 734 608 586 831 815  51 890
  43 825 230 188 270 962 526 826 595 640  20 738  45 387 731 309  43 766
 932 389 980 162 213 426 473 979 210 270 183 424 720 270  56 742  49 763
 316 426 106 917 587  47 171 456 293 726 792 254 387 232 244 759 777  13
 337  64 414 720 320 913 861  15 671 230]
[693.41 666.3  187.12 376.   495.79 667.18 405.73 705.65 448.57 773.86
 707.4   48.97 142.53 602.47 219.48 712.65 114.55 501.91 427.59 584.98
 454.69 334.03 312.17  86.57 678.54 399.61 802.71 836.81 611.21 641.82
 531.64 512.41 726.64 712.65  44.6  778.23  37.6  721.39 201.11 164.39
 236.09 841.19 459.94 722.27 520.28 559.62  17.49 645.32  39.35 338.4
 639.2  270.19  37.6  669.8  814.95 340.15 856.92 141.65 186.25 372.5
 413.6  856.05 183.63 236.09 160.02 370.75 629.58 236.09  48.97 648.81
  42.85 667.18 276.31 372.5   92.69 801.84 513.28  41.1  149.52 398.73
 256.2  634.82 692.54 222.1

**3) Trabajemos con pandas**

* Importa pandas y usa un alias para poder utilizar sus recursos
* Cargar como dataframe de pandas el csv 05_05_imdb_titulos.csv y mostrar sus 5 primeros registros
* Cargar como dataframe de pandas el csv 05_05_imdb_elenco.csv y mostrar sus 5 primeros registros
* Mostrar el número de registros del dataframe de titulos
* Mostrar el número de registros del dataframe de elenco
* Mostrar las 5 peliculas más antiguas del listado de titulos
* Mostrar las peliculas que en el titulo tienen la palabra "Dracula". También mostrar el número total de peliculas que coincidan con este requisito
* Mostrar los 10 titulos más comunes (que más se repiten)
* Mostrar cual fue la primer pelicula hecha titulada "Romeo and Juliet" 
* Listar todas las peliculas que contengan la palabra "Exorcist" ordenadas de la más vieja a la más reciente
* Mostrar cuantas peliculas fueron hechas en el año 1950
* Mostrar cuantas peliculas fueron hechas de 1950 a 1959
* Mostrar todos los roles o papeles que hubo en la pelicula "The Godfather". También mostrar el número total de coincidencias
* Mostrar el elenco completo ordenado por la clasificacion "n" de la pelicula "Dracula" de 1958
* Mostrar cuantos papeles de "Bruce Wayne" han sido hechos en la historia de las peliculas
* Mostrar cuantos papeles ha hecho "Robert De Niro" en su carrera
* Listado de papeles como protagonista (n=1) que tuvo el actor "Charlton Heston" en la década de los 60's, ordenado por año de forma descendente
* Mostrar cuantos papeles para actores hubo en la década de los 50's
* Mostrar cuantos papeles para actrices hubo en la década de los 50's

In [53]:
# Completa el ejercicio aquí
import pandas as pd
df_titulos = pd.read_csv("05_05_imdb_titulos.csv")
df_elenco = pd.read_csv("05_05_imdb_elenco.csv")


title  year                         name  \
0                          Closet Monster  2015                     Buffy #1   
1                         Suuri illusioni  1985                       Homo $   
2                     Battle of the Sexes  2017                      $hutter   
3                    Secret in Their Eyes  2015                      $hutter   
4                              Steve Jobs  2015                      $hutter   
...                                   ...   ...                          ...   
3564645                    Stuttur Frakki  1993    Sveinbj?rg ??rhallsd?ttir   
3564646                           Foxtrot  1988            Lilja ??risd?ttir   
3564647  Niceland (Population. 1.000.002)  2004    Sigr??ur J?na ??risd?ttir   
3564648                      U.S.S.S.S...  2003  Krist?n Andrea ??r?ard?ttir   
3564649                 Bye Bye Blue Bird  1999                 Rosa ? R?gvu   

            type                character     n  
0          actor                  Buffy 4  31.0  
1          actor                   Guests  22.0  
2          actor          Bobby Riggs Fan  10.0  
3          actor          2002 Dodger Fan   NaN  
4          actor  1988 Opera House Patron   NaN  
...          ...                      ...   ...  
3564645  actress               Flugfreyja  24.0  
3564646  actress                     D?ra  24.0  
3564647  actress             Woman in Bus  26.0  
3564648  actress   Afgr.dama ? bens?nst??  17.0  
3564649  actress        Pensionatv?rtinde   NaN  

[3564650 rows x 6 columns]

In [159]:
print(df_titulos.head())
print(df_elenco.head())
print(f"El dataframe titulos tiene {df_titulos.shape[0]} filas y {df_titulos.shape[1]} columnas")
print(f"El dataframe elenco tiene {df_elenco.shape[0]} filas y {df_elenco.shape[1]} columnas")
#Usamos print (aunque queda peor) para que se quede en el terminal.
print(df_titulos.sort_values(by=['year']).head(5))
#Listamos los elementos de df_titulos que contienen la palabra "Dracula" en el título de la película
print(df_titulos[df_titulos['title'].str.contains('Dracula')==True])
#Mostramos cuántas películas contienen Drácula en su título (cuidado con el acento)
print(f"Existen {df_titulos[df_titulos['title'].str.contains('Dracula')==True].shape[0]} películas sobre Drácula en el dataframe")

#Genereamos una lista con los títulos ordenados por el número de veces que se repiten
listaTitulosOrdenadaPorRepeticiones = df_titulos['title'].value_counts().index.to_list()
#Mostramos los 10 primeros títulos de la lista
print(listaTitulosOrdenadaPorRepeticiones[:10])

#Ordenamos por fecha las películas que tienen como título 'Romeo and Juliet':
df1 = df_titulos[df_titulos['title'] == ('Romeo and Juliet')].sort_values(by=['year'])
#Nos quedamos con el valor del dataframe filtrado que tiene la menor fecha
print(f"La película buscada es {df1['title'][df1['year'] == df1['year'].min()].to_list()[0]} y es del año {df1['year'][df1['year'] == df1['year'].min()].to_list()[0]}")

#Ordenamos por fecha las películas que tienen como título 'Exorcist' ordenadas por fecha de menor a mayor:
print(df_titulos[df_titulos['title'].str.contains('Exorcist') == True].sort_values(by=['year']))

#Películas hechas en el año 1950
print(df_titulos[df_titulos['year'] == 1950])

#películas hechas entre 1950 y 1959 ambos inclusive.
print(df_titulos[((df_titulos['year'] >= 1950) & (df_titulos['year']<= 1959))].sort_values(by=['year']))




                                   title  year
0                                 Mahler  1974
1           Ogon, voda i... mednye truby  1968
2  Ana Nojoom bent alasherah wamotalagah  2014
3                      Malu de Bicicleta  2010
4             Nazareno Apostol: Boy Ahas  1989
                  title  year      name   type                character     n
0        Closet Monster  2015  Buffy #1  actor                  Buffy 4  31.0
1       Suuri illusioni  1985    Homo $  actor                   Guests  22.0
2   Battle of the Sexes  2017   $hutter  actor          Bobby Riggs Fan  10.0
3  Secret in Their Eyes  2015   $hutter  actor          2002 Dodger Fan   NaN
4            Steve Jobs  2015   $hutter  actor  1988 Opera House Patron   NaN
El dataframe titulos tiene 230407 filas y 2 columnas
El dataframe elenco tiene 3564650 filas y 6 columnas
                                                    title  year
13229                                          Miss Jerry  1894
103233          

In [179]:
#Mostrar todos los roles o papeles que hubo en la pelicula "The Godfather". También mostrar el número total de coincidencias 
#Se muestran por orden alfabético
print(df_elenco[df_elenco['title'] == 'The Godfather'].sort_values(by = ['name']))
print(f"El número de actores y roles es de {df_elenco[df_elenco['title'] == 'The Godfather'].sort_values(by = ['name']).shape[0]} actores")

# Mostrar el elenco completo ordenado por la clasificacion "n" de la pelicula "Dracula" de 1958
print(df_elenco[((df_elenco['title'] == 'Dracula') & (df_elenco['year'] == 1958))].sort_values(by = ['n']))

#Mostrar cuantos papeles de "Bruce Wayne" han sido hechos en la historia de las peliculas
print(df_elenco[((df_elenco['character'] == 'Bruce Wayne'))].sort_values(by = ['title']))

#Mostrar cuantos papeles ha hecho "Robert De Niro" en su carrera
print(df_elenco[((df_elenco['name'] == 'Robert De Niro'))])

#Listado de papeles como protagonista (n=1) que tuvo el actor "Charlton Heston" en la década de los 60's, ordenado por año de forma descendente
print(df_elenco[((df_elenco['name'] == 'Charlton Heston') & (df_elenco['n'] == 1) & (df_elenco['year'] >= 1960) & (df_elenco['year'] <= 1969))].sort_values(by = ['year']))

#Mostrar cuantos papeles para actores hubo en la década de los 50's
print(df_elenco[((df_elenco['year'] >= 1950) & (df_elenco['year'] <= 1959))].shape[0])

                 title  year            name     type  \
2244677  The Godfather  1972      Abe Vigoda    actor   
1260607  The Godfather  1972     Al Lettieri    actor   
1381599  The Godfather  1972      Al Martino    actor   
1642816  The Godfather  1972       Al Pacino    actor   
1847779  The Godfather  1972      Alex Rocco    actor   
...                ...   ...             ...      ...   
1146749  The Godfather  1972       Tony King    actor   
1279489  The Godfather  1972        Tony Lip    actor   
2530787  The Godfather  1972   Tybee Brascia  actress   
1808526  The Godfather  1972  Victor Rendina    actor   
1952800  The Godfather  1972     Vito Scotti    actor   

                       character     n  
2244677                   Tessio  11.0  
1260607                 Sollozzo   9.0  
1381599           Johnny Fontane  16.0  
1642816         Michael Corleone   2.0  
1847779               Moe Greene  22.0  
...                          ...   ...  
1146749        Tony - Stable

In [190]:
print(f"Ha habido {df_elenco[((df_elenco['year'] >= 1950) & (df_elenco['year'] <= 1959))].shape[0]} papeles en la década de los 50")
#Mostrar cuantos papeles para actores hubo en la década de los 50's
print(f"{df_elenco[((df_elenco['year'] >= 1950) & (df_elenco['year'] <= 1959) & (df_elenco['type'] == 'actor'))].shape[0]} papeles han sido interpretados por actores y ")
#Mostrar cuantos papeles para actrices hubo en la década de los 50's
print(f"{df_elenco[((df_elenco['year'] >= 1950) & (df_elenco['year'] <= 1959) & (df_elenco['type'] == 'actress'))].shape[0]} por actrices")

Ha habido 210002 papeles en la década de los 50
153998 papeles han sido interpretados por actores y 
56004 por actrices
